name: Run test when pushed to master
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker login -u ${{secrets.DCOKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD }}
      run: docker build -t buildmyfrontend -file Dockerfile.dev .
      run: docker run -e CI=true buildmyfrontend npm test