name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Using a pre-built action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Using a pre-built action

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Using a pre-built action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t myfrontendbuild -f Dockerfile.dev

      - name: Run test after code merge
        run: |
          docker run -e CI=true myfrontendbuild npm test